### ISSUE TITLE
List view context menu issue

### ISSUE THREAD

**Issue by froggz19** [JosefNemec/Playnite#1658]
**Describe the bug**
Context menu not getting updated when right clicking on items in list view.

**To Reproduce**
Add at least one custom action for any game in your library, right click on that game to open the context menu then right click on some other game.

[Video](https://streamable.com/zjz5f)

**Comment by JosefNemec** [comment]
Fixed by 34afe9a5759580a7bee4d95bc75f54986c1063aa in `devel8`.

**Comment by froggz19** [comment]
Idk if devel8 was pushed to master but I still have this problem. As you can see in the video, the context menu is not updated when right clicking on games in list view. Selecting the game with left click before opening the context menu seems to "fix" it...

https://user-images.githubusercontent.com/8935954/103157212-01ce1a80-47b1-11eb-8aad-7f2130804ee8.mp4
