### ISSUE TITLE
Playnite not pulling icons from installed Epic Games Store games

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#1678]
**Describe the bug**
Intented behaviour is that Playnite pulls game icons for installed games from their executables, but currently no icons are being pulled even when it's supposed to.

**Comment by JosefNemec** [comment]
To clarify, this only happens when metadata are being downloaded. If the game is being imported for the first time and it's also installed, then the icon is properly added.

**Comment by JosefNemec** [comment]
Already fixed in `devel8` by some commit I forgot about.

**Comment by Zinnatis** [comment]
I can confirm this is still an issue in version 8.11.
Repro:
* I've added all my accounts, first with "Import not installed games" unchecked.
* I changed all stores settings to import not installed games, then "Update all"
* Only Epic Games Store games have no icons imported. All the other metadata is there.
![image](https://user-images.githubusercontent.com/8620027/108623586-070db580-7440-11eb-8566-e606f8e63aea.png)

**Comment by ThomasDNguyen** [comment]
Date: April 1st, 2021
Version: latest (8.12)
Status: the same bug persists. All Epic Game Store games lack icons with a few even missing game artwork (which is most noticeable when in full-screen mode)

![image](https://user-images.githubusercontent.com/26536436/113310293-c04d8e00-9310-11eb-964c-a8d029a7cefd.png)

**Comment by JosefNemec** [comment]
https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider

**Comment by alpe12** [comment]
> https://github.com/JosefNemec/Playnite/wiki/Feature-table-based-on-library-provider

This says that Epic supports icons for installed games.
None of my Epic installed games have icons.

And if I go to Edit > Media, and try to import icon "from Play action" it says "Cannot get icon if Play action is missing or is set to URL".

**Comment by kongomongo** [comment]
The above link is dead and I am experiencing this issue. What can be done?
