### ISSUE TITLE
Attempting to install extensions by opening pext files fails

### ISSUE THREAD

**Issue by darklinkpower** [JosefNemec/Playnite#2113]
**Describe the bug**
Attempting to install extensions by opening pext files fails. Playnite's window is brought to focus but doesn't prompt the installation dialogue. Installing this way has never worked for me since this new feature was introduced.

Log
```
13-11 08:26:13.003|INFO|PlayniteApplication:Executing command "Focus" from pipe with arguments ""
13-11 08:26:13.008|INFO|PlayniteApplication:Application already running, shutting down.
```

Video: https://cdn.discordapp.com/attachments/456880338346704913/776818623478104145/1oq3s1izAn.mp4

**Diagnostics ID**
4aee1e1d-1863-44f5-a9da-9fff884b59c3

**Comment by JosefNemec** [comment]
I can't reproduce it, does it happen always or is it a random thing?

**Comment by darklinkpower** [comment]
Random, but this issue happens more times than it succeeds to me. I think it never happens if I attempt to install this way just after Playnite launched, only if it has been running for a while.

**Comment by JosefNemec** [comment]
Do not clear the logs please, information from older app instances might be very useful to debugging an issue.

**Comment by darklinkpower** [comment]
My bad, yeah I usually clean them.

Here's a diag. package with the issue without cleaning. It can be seen that this issue only happens when trying to install extensions but it works correctly when trying to install themes.

951af10a-7c0b-45a2-a522-388f5b4ad5c5

Last 3 actions in log:
1. Attempt to install extension (No installation message)
2. Attempt to install theme (Installation message shows correctly)
3. Attempt to install extension (No installation message)

**Comment by JosefNemec** [comment]
I can't reproduce it.

Please attach export of following registry keys:
HKEY_CURRENT_USER\Software\Classes\.pthm
HKEY_CURRENT_USER\Software\Classes\.pext
HKEY_CURRENT_USER\Software\Classes\Playnite.ext

**Comment by darklinkpower** [comment]
I don't have `HKEY_CURRENT_USER\Software\Classes\Playnite.ext` in my PC registry, only the other two

[Registry keys.zip](https://github.com/JosefNemec/Playnite/files/5547306/Registry.keys.zip)

Only difference between them is here:
![imagen](https://user-images.githubusercontent.com/1389286/99274261-bc045680-27ef-11eb-81f8-6690d9fcda0a.png)


![imagen](https://user-images.githubusercontent.com/1389286/99274202-a727c300-27ef-11eb-85b0-2c82dede68eb.png)

**Comment by darklinkpower** [comment]
![imagen](https://user-images.githubusercontent.com/1389286/99275305-f1f60a80-27f0-11eb-9e43-b0d762eaa7ed.png)
![imagen](https://user-images.githubusercontent.com/1389286/99275278-e99dcf80-27f0-11eb-8e6e-0152cac38a12.png)
![imagen](https://user-images.githubusercontent.com/1389286/99275324-f91d1880-27f0-11eb-8dbd-019c95329e95.png)
![imagen](https://user-images.githubusercontent.com/1389286/99275351-01755380-27f1-11eb-89e7-ba3d4f55f9fd.png)
![imagen](https://user-images.githubusercontent.com/1389286/99275418-13ef8d00-27f1-11eb-8957-14c9a98b0aef.png)

**Comment by JosefNemec** [comment]
That means that some 3rd party modified that .pext entry. Delete all those keys I mentioned and restart Playnite, it should fix itself.

**Comment by darklinkpower** [comment]
I just deleted all the keys and the issue is still here. And I don't know if something modified the key externally since I've not used any software that accesses registry keys, unless Windows itself did it for some reason.

```
16-11 09:59:24.408|INFO|PlayniteApplication:Application already running, shutting down.
16-11 09:59:24.536|INFO|PlayniteApplication:Executing command "ExtensionInstall" from pipe with arguments "C:\Users\Brandon\Downloads\SteamNite_2_5.pthm"
16-11 09:59:33.261|INFO|PlayniteApplication:Executing command "Focus" from pipe with arguments ""
16-11 09:59:33.267|INFO|PlayniteApplication:Application already running, shutting down.
16-11 10:00:29.452|INFO|PlayniteApplication:Executing command "Focus" from pipe with arguments ""
16-11 10:00:29.451|INFO|PlayniteApplication:Application already running, shutting down.
16-11 10:00:32.074|INFO|PlayniteApplication:Executing command "Focus" from pipe with arguments ""
16-11 10:00:32.074|INFO|PlayniteApplication:Application already running, shutting down.
```

New pext generated key looks the same as the pthm key
![imagen](https://user-images.githubusercontent.com/1389286/99276959-d855c280-27f2-11eb-9a1d-a6d652e61af0.png)

![imagen](https://user-images.githubusercontent.com/1389286/99277005-e7d50b80-27f2-11eb-856a-3bfee9f42efa.png)

**Comment by JosefNemec** [comment]
Closing, not caused or fixable on Playnite's side based on Discord discussion.
