### ISSUE TITLE
P9 Beta: Removing a game from the game options menu in fullscreen mode leaves you stuck at an empty game details page

### ISSUE THREAD

**Issue by Super1337Boy** [JosefNemec/Playnite#2458]
**Describe the bug**
When removing a game from favorites via the game options menu on the game details page in fullscreen, I get an empty game page like the one below instead of being bumped to the next game. The only way to move on is to hit the right bumper on the controller to move to the next game.

**To Reproduce**
Go to the game options menu for a game in fullscreen, and remove the game.

**Screenshots**
![Playnite_bug](https://user-images.githubusercontent.com/6672819/132336752-c8f606fb-4f14-426d-add1-d289c707efa4.png)

**Comment by JosefNemec** [comment]
Fixed in devel.

**Comment by Super1337Boy** [comment]
This issue is still present in Beta 2, but I just realized that it only happens while my Favorites Quick Filter is active.

In other words, you have to use a Quick Filter that filters based on favorites for this to happen. I guess it happens because the the game gets remove from the active filter.

**Comment by JosefNemec** [comment]
I can't reproduce it with beta 2. Make sure that you really are using beta 2 build. If you are sure, then please attach video and diagnostics package.

**Comment by Super1337Boy** [comment]
Yes, I'm positive that I'm on Beta 2. I uploaded diag. package: 4cf234fa-aa94-4279-aa66-de6761a472b2

Video of the issue: 

https://user-images.githubusercontent.com/6672819/132840727-4721bd73-5a6c-43d6-a7fc-7334a904c514.mp4

**Comment by JosefNemec** [comment]
Thanks, this is technically a different issue since the original was about removing a game and your video shows game being removed from favorites. I'll fix it.

**Comment by Super1337Boy** [comment]
Sorry if the original discription was unclear. I ment  removing from favorites all along, but I guess the same thing happened when removing games from the database as well. Good thing we figured it out at least.

**Comment by JosefNemec** [comment]
Fixed in devel.
