### ISSUE TITLE
Playnite 8: Bulk metadata import not updating game name

### ISSUE THREAD

**Issue by ferrazpedro** [JosefNemec/Playnite#2482]
**Describe the bug**
Right now, if we select to update the name of the games in bulk metadata import, they aren't being updated.

**To Reproduce**
Use the bulk metadata import with any metadata extension that supports auto name update.

**Screenshots**
I just imported the metadata of this game with the bulk option:
![image](https://user-images.githubusercontent.com/37643357/133012453-f126ab79-169e-4c9c-aef8-6612a9ce2ccf.png)

The name it grabs from the database:
![image](https://user-images.githubusercontent.com/37643357/133012475-03c6503d-1d49-4faa-8a1d-4edd08b4c0df.png)

The config I'm using:
![image](https://user-images.githubusercontent.com/37643357/133012498-9afbe211-830a-4188-ae08-ad0fecb5452a.png)

**Diagnostics ID**
(Can't post a diagnose right now, will update when I can)

**Comment by JosefNemec** [comment]
Looks like fixed in devel (P9).

**Comment by ferrazpedro** [comment]
I have recently tested this in Playnite 9.6 and it's still happening D:

**Comment by polson** [comment]
I'm the developer of the ScreenScraper.fr plugin used here.  I think it's possible there is some underlying issue in Playnite that is not working when using the `name` field.  I do have this field specified as handled by the plugin.  

However what I am seeing is that the extension does not run at all when doing bulk metadata download of name field only.  It does run when doing name field + cover image, but it still doesn't update the name.  

Here is a link to the extension:
https://github.com/polson/screenscraper-playnite-metadata-plugin

**Comment by polson** [comment]
Okay after some investigation, I do think there is some issue in Playnite.  This is reproducible with the IGDB plugin.

Steps:
1. Do a bulk metadata download for a single game with the following settings:
![image](https://user-images.githubusercontent.com/302882/160302116-3f3c4642-8f4e-4b29-9136-bc05da785648.png)


2. Select only Name field, and IGDB plugin
![image](https://user-images.githubusercontent.com/302882/160302144-261ba6d6-8e50-40f3-908d-37962cfd4169.png)

3. Select `Download Metadata`

Expected: Metadata is downloaded
Actual: Nothing happens, no network call is made (verified with Charles proxy)

Repeating these steps with Name and Genre selected does make the network call and work as normal:

![image](https://user-images.githubusercontent.com/302882/160302193-f061c710-4148-48f7-886d-9a0a835b9e9e.png)

**Comment by polson** [comment]
Another issue I am seeing using IGDB plugin:  When selecting both `Name` and `Developer` together in bulk metadata download options, I can verify the network call is made.  However it is not updating the Name field, only the `Developer` field.

Steps to repro:
1. Edit an existing game and add a space to the end of the game name:
![image](https://user-images.githubusercontent.com/302882/160302751-9c441a58-150d-413f-a81c-515d09642fa1.png)

2. Edit the game to remove the `Developers` field

3. Run metadata import with these settings, and the game selected
![image](https://user-images.githubusercontent.com/302882/160302772-94eeff13-95b9-4dbf-8e86-ec57cf331b00.png)

![image](https://user-images.githubusercontent.com/302882/160302805-4c2476db-88fc-41d8-81c2-affc7e6d7d36.png)

Notice when checking the game details, the developer field is updated.  However the name is not.

**Expected**:  The space is gone from the game name
**Actual**: The space is still there.
![image](https://user-images.githubusercontent.com/302882/160302843-3d4655fc-f6db-4a86-802e-1fb238d78b5f.png)

I verified that the network call to IGDB was made and the proper name was returned.  However it was not updated:

![image](https://user-images.githubusercontent.com/302882/160302877-7ea41b6c-4d09-46c1-a4c0-0de11bda5797.png)

**Comment by JosefNemec** [comment]
Fixed in master.
