### ISSUE TITLE
Playnite Fullscreen preventing Sleep / Hibernate

### ISSUE THREAD

**Issue by ionutrobert** [JosefNemec/Playnite#2932]
### Bug Description

Running the powercfg - requests in cmd shows the audio driver preventing sleep while Playnite fullscreen is on. 

Changing the audio setting to Waveout API while mute when in background option is on: If the Playnite fullscreen is not the active window (focused), the pc would sleep. CMD window running "powercfg -requests" does not show anything that is preventing the PC from sleeping. (Sleep still does not work while Playnite Fullscreen window is focused)

### To Reproduce

Set Stand By timer in windows power settings to 1 min and launch Playnite in Fullscreen mode.

Administrator cmd: "powercfg -requests" will show whatever process/driver is preventing the PC from sleeping/hibernate.

### Diagnostics ID

e5173c13-4dde-407d-b24a-01baa79b1534

### Screenshots

Fullscreen:
https://gyazo.com/5d78d919c6567a5240bb8108dabd75d7
On another PC I tried, cmd showed System: [DRIVER] Legacy Kernel Caller preventing sleep with Playnite Fullscreen. (I think that suggests audio/media playing)

Desktop:
https://gyazo.com/d8f7a54204c69a021a1fb9cb383f9971

**Comment by IowaMan** [comment]
I was also getting this issue even when not in fullscreen mode. Windows Events Power-Troubleshooter says: Wake Source: Timer - Playnite.DesktopApp.exe
This triggers nearly EXACTLY every four minutes (just 4 seconds short, so every 236 seconds.) 
Might want to check any timers that last near that long.

**Comment by JosefNemec** [comment]
Desktop mode doesn't have any 4 minute timers. The only timer it has is 4 hour one for update check. It must be some extension you have installed.

**Comment by MrSco** [comment]
I’m having issues sleeping my system while full screen is running. The screen sleeps but not windows/system itself. Desktop mode sleeps screen and system just fine however. Any updates or workarounds for this? 

Thanks!

**Comment by maxwellhibbert** [comment]
I also have this issue, only in fullscreen.

**Comment by JasSuri** [comment]
I have this issue when playnite is in fullscreen.

**Comment by lyndonguitar** [comment]
I also have this issue. This is preventing sleep / hibernate because when playnite is open apparently 
"An audio stream is currently in use.". This is more apparent with Steam Deck because I am constantly using the power button to sleep, only for it to wake right back up because of this.

I have tested thoroughly and I can validate that it's Playnite that's causing this "audio stream is currently in use."
It's weird because it was fine for many months of using Steam Deck and suddenly this problem appeared. Although I can confirm Playnite has been recently updated. Haven't tested each version yet to see if the problem will go away with previous versions

For the meantime I used the following cmd commands and that seemed to fix the problem.

powercfg -REQUESTSOVERRIDE DRIVER "AUDIO DEVICE NAME" SYSTEM.

**Comment by L0nZz** [comment]
Here's a temporary fix until it's eventually patched.

Scan:
powercfg /requests

Override:
powercfg /requestsoverride DRIVER "Device name" SYSTEM
powercfg /requestsoverride PROCESS software.exe SYSTEM

Undo:
powercfg /requestsoverride DRIVER "Device name"
powercfg /requestsoverride PROCESS software.exe


Example:

C:\Windows\System32>powercfg /requests
DISPLAY:
None.

SYSTEM:
[DRIVER] USB Audio 2.0 (USB\VID_1235&PID_8211&MI_00\8&175349a7&0&0000)
An audio stream is currently in use.
[PROCESS] \Device\HarddiskVolume5\Playnite\Playnite.FullscreenApp.exe

AWAYMODE:
None.

EXECUTION:
None.

PERFBOOST:
None.

ACTIVELOCKSCREEN:
None.


C:\Windows\System32>powercfg /requestsoverride DRIVER "USB Audio 2.0" SYSTEM

C:\Windows\System32>powercfg /requestsoverride PROCESS Playnite.FullscreenApp.exe SYSTEM



Solution:
powercfg /requestsoverride DRIVER "USB Audio 2.0" SYSTEM
powercfg /requestsoverride PROCESS Playnite.FullscreenApp.exe SYSTEM

Undo:
powercfg /requestsoverride DRIVER "USB Audio 2.0"
powercfg /requestsoverride PROCESS Playnite.FullscreenApp.exe

**Comment by zomgugoff** [comment]
The workaround listed does not appear to be helping with screen-waking issue from a display-off state. (Not in sleep/hibernate)

**Comment by Hpridham** [comment]
I'm experiencing this issues. I've tried to override playnite and my audio sources in cmd powercfg to no avail. I know the powercfg option can work because it stopped my oculus app from preventing sleep.

**Comment by TheOneOgre** [comment]
As stated in the previous comment, the workaround does not work, using a fresh Windows 11 22H2 install and tried 24H2 to no avail.

Trying to set this up as a living room gaming setup that's easy to use and will act more like a console with auto standby and such.

**Comment by kakobubu** [comment]
> As stated in the previous comment, the workaround does not work, using a fresh Windows 11 22H2 install and tried 24H2 to no avail.
> 
> Trying to set this up as a living room gaming setup that's easy to use and will act more like a console with auto standby and such.

Same problem here, have you find something to correct it ?

**Comment by MrSco** [comment]
> I also am having this sleep issue, PlayNite's audio in fullscreen mode is keeping computer awake. PlayNite need's a true music disable not just lower volume to 0 because windows still thinks there is audio playing... running powercfg -requests confirms it

They just need a disable music button instead of just a volume slider. How has it been 2 years and this not implemented yet. So ez. Jeebus

**Comment by Hpridham** [comment]
Code contributions haven't been accepted since late 2023, when the Playnite 11 rewrite was started. There have been some exceptions but it's painful to have this tool stagnate. Actively looking for alternatives.

**Comment by JosefNemec** [comment]
> They just need a disable music button instead of just a volume slider. How has it been 2 years and this not implemented yet. So ez. Jeebus

We already stop music playback completely if you set volume to 0, as you can see [here](
https://github.com/JosefNemec/Playnite/blob/master/source/Playnite.FullscreenApp/ViewModels/FullscreenAppViewModel.cs#L566). I don't know why it doesn't fix this specific issue.

> There have been some exceptions but it's painful to have this tool stagnate

The fact that it's been taking this long is painful to me as well. It's also painful to work on Playnite 10's code base for me, which is why this complete rewrite is happening and why I'm prioritizing it over development of additional P10 updates.

I'll try to find some time and look into this over next week to see if this can be at least handled via some workaround.

**Comment by JosefNemec** [comment]
Fixed in master. Playnite will now explicitly close audio device after 45 seconds of either no audio sound being played or Playnite being out of focus.

Keep in mind that plugins and themes can play audio on their own using their own method which we can't control. This fix only affects audio playback directly controlled by Playnite itself.

**Comment by MrSco** [comment]
Not fixed on v10.37

If playnite Fullscreen is in focus, it still prevents sleep

**Comment by JosefNemec** [comment]
You have to have background music playback disabled if you want sleep to work while Playnite is in focus. Because otherwise Playnite will obviously play background music and prevent PC to doing into sleep.

Also make sure it's not a plugin/theme issue, some integrate video and audio playback that could be causing issues with this.

**Comment by MrSco** [comment]
background music is set to 0

tested with default theme. using standard library addons... 

<img width="410" height="273" alt="Image" src="https://github.com/user-attachments/assets/054b5a85-59df-4513-bbf6-e8234d3f9a81" />

**Comment by JosefNemec** [comment]
Can you run `powercfg /requests` to make sure it's Playnite preventing sleep and not something else on your system?

**Comment by MrSco** [comment]
Yes I confirmed by running that command. And also by closing playnite or alt tabbing to desktop taking playnite out of focus allows sleep. Only when playnite is in foreground does it not sleep

**Comment by e270889o** [comment]
Still happening. Powercfg requests shows nvidia preventing sleep only when playnite fullscreen is the focused window. 

Last version. W11

**Comment by JosefNemec** [comment]
If it shows "nvidia" is preventing sleep, then it's some issue on nvidia's side.

**Comment by e270889o** [comment]
> If it shows "nvidia" is preventing sleep, then it's some issue on nvidia's side.

I will upload screenshots but the problem is caused by playnite. 

It says nvidia because the audio is going out by hdmi to the tv. So it’s using nvidia hd audio

Playnite fullscreen focus screen. No sleep and nvidia audio on powercfg request 

Playnite fullscreen background. No sleep and nvidia audio on powercfg request 

Playnite fullscreen background after a few minutes. Correct sleep. No powercfg entrie

Playnite desktop. Correct sleep. No powercfg entrie. 

Removed al audio files from installation. No change. Turn volume down on playnite settings. No change. No sleep 
Default theme, toggle handheld theme. No change in both. No sleep.

Something on fullscreen is streaming audio and nvidia is picking up that. Even with volume 0 it’s emitting something. 

Can I help you with some logs or something? Thanks
