### ISSUE TITLE
Failed to open library database after update from 3.1 to 3.2

### ISSUE THREAD

**Issue by deextercz** [JosefNemec/Playnite#327]
It occurs everytime when I open playnite and after update.
![capture](https://user-images.githubusercontent.com/23039506/34162734-0b3a7f60-e4d5-11e7-81e1-85b0e23001e3.PNG)

[bug.zip](https://github.com/JosefNemec/Playnite/files/1572029/bug.zip)

[games.zip](https://github.com/JosefNemec/Playnite/files/1572032/games.zip)

**Comment by JosefNemec** [comment]
Looks that more that one Playnite instance tried to access your game database. That shouldn't normally happen since there's a check to make sure that only once instance can run. Anyway I'll make it so database file cannot be opened by multiple processes to prevent this from happening.

**Comment by JosefNemec** [comment]
Fix released in 3.3 51f855167d9da4aa2508f86eaabdbb7366a5addd

**Comment by CorruptComputer** [comment]
@JosefNemec This is still happening, and I figured out by using [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see what was using the file. And after some testing I was able to find that Google Drive will lock the file while backing up, which will cause Playnite to fail to initialize because it cannot get a lock on the DB as it is already in use.

**Comment by JosefNemec** [comment]
Thanks @CorruptComputer, I'll look into it.

**Comment by JosefNemec** [comment]
I have tweaked messaging when this issue occurs (Google Drive or other process holds the file), to make it more clear what to do to fix it. Also DB corruption should no longer occur thanks to changes in 3.3.

Overall that's about all I can do about it. If some other process holds the file there's nothing I can do to release it safely (I guess Google Drive doesn't use shadow copies to backup files like OneDrive does).

**Comment by CorruptComputer** [comment]
Could you not make a temporary copy into RAM and use that until the file is done backing up? Then get a lock and save the changes.

**Comment by JosefNemec** [comment]
I could but that would increase RAM usage a lot.

**Comment by CorruptComputer** [comment]
The DB (for me at least) is only about 80mb which is almost nothing for ram usage. Also it would be temporary, so ram would go back down in less than a minute (depending on internet speeds).

**Comment by JosefNemec** [comment]
There are more problems, I don't know how long it would take for 3rd party process to close the db. So what if user restarts Playnite in the mean time? Or anything else happens, keeping whole DB in memory is no go for me.

**Comment by deextercz** [comment]
Could you lock db on computer start and make playnite as service?
čt 4. 1. 2018 v 10:19 odesílatel Josef Nemec <notifications@github.com>
napsal:

**Comment by JosefNemec** [comment]
@deextercz Apart from the fact that it would add huge amount of overhead for UI<->DB communication, it would also mean that apps like Google Drive would not be able to backup DB anymore because it would be always locked by Playnite.

**Comment by CorruptComputer** [comment]
Ah fair enough, how about a temporary copy of the DB which is used until the original can be locked? That would fix the user restarting the app as it would keep the changes. Also the temp copy probably shouldn't be kept in the same folder as the original, and rather be in the systems temporary files by default (user configurable of course).

**Comment by JosefNemec** [comment]
I guess temp file could be a solution, but that has other issues :) What if the db file is quite large? It would slow down startup and shutdown and also increased disk space usage.

We could use shadow copy if the file is locked, but shadow copies can't be changed so Platynite would be in some "read only" mode.

**Comment by CorruptComputer** [comment]
Yeah there's not really a 'nice' way to go about this. Pretty much every solution has it's drawbacks, it's really up to you how you go about it.

**Comment by JosefNemec** [comment]
Released in 3.4, Playnite will now show appropriate error message when DB is being held by other process and it will not corrupt it. I'l try to make some other changes to completely prevent this from happening in future with #363, which will use completely different update process.
