### ISSUE TITLE
Blend Previews Not Working in Playnite 10.35

### ISSUE THREAD

**Issue by CallMeKaaze** [JosefNemec/Playnite#3995]
### Bug Description

Attempting to edit .xaml styles in Blend produces this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Object reference not set to an instance of an object.	Theme	C:\Applications\Playnite\Themes\Desktop\StardustCustom\Views\DetailsViewGameOverview.xaml	1	

StackTrace
at Playnite.Converters.InvertedBooleanToVisibilityConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)
   at System.Windows.StyleHelper.GetInstanceValue(UncommonField`1 dataField, DependencyObject container, FrameworkElement feChild, FrameworkContentElement fceChild, Int32 childIndex, DependencyProperty dp, Int32 i, EffectiveValueEntry& entry)
   at System.Windows.StyleHelper.GetChildValueHelper(UncommonField`1 dataField, ItemStructList`1& valueLookupList, DependencyProperty dp, DependencyObject container, FrameworkObject child, Int32 childIndex, Boolean styleLookup, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetChildValue(UncommonField`1 dataField, DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetValueFromTemplatedParent(DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, FrameworkElementFactory templateRoot, EffectiveValueEntry& entry)
   at System.Windows.FrameworkElement.GetValueFromTemplatedParent(DependencyProperty dp, EffectiveValueEntry& entry)
   at System.Windows.FrameworkElement.GetRawValue(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& entry)
   at System.Windows.FrameworkElement.EvaluateBaseValueCore(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& newEntry)
   at System.Windows.DependencyObject.EvaluateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry newEntry, OperationType operationType)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)

### To Reproduce

Open DetailsViewGameOverview.xaml in Blend and edit the style.

### Diagnostics ID

N/A

### Screenshots

![Image](https://github.com/user-attachments/assets/49587ce5-7433-4cf1-8f69-2de18206229a)

**Comment by JosefNemec** [comment]
Does it happen only with this theme or with completely new one generated via Toolbox as well?

**Comment by CallMeKaaze** [comment]
It seems to only happen with this theme, it's the Stardust theme by darklinkpower, he sent me to post about the issue here.

**Comment by JosefNemec** [comment]
Fixed in master

**Comment by darklinkpower** [comment]
I'm still experiencing this issue in Playnite v10.37 and after updating the theme to ThemeApiVersion 2.8.0

![Image](https://github.com/user-attachments/assets/de32aa24-2412-4c1e-a7ce-e1a7a38df6d6)

I'm using it like this:

```
<Border Tag="{PluginStatus Plugin=felixkmh_Extras_Plugin, Status=Installed}"
        Visibility="{Binding RelativeSource={RelativeSource Self}, Path=Tag, Converter={StaticResource InvertedBooleanToVisibilityConverter}}" />
```

```
NullReferenceException: Object reference not set to an instance of an object.

StackTrace:

at Playnite.Converters.InvertedBooleanToVisibilityConverter.Convert(Object value, Type targetType, Object parameter, CultureInfo culture)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.AttachOverride(DependencyObject target, DependencyProperty dp)
   at System.Windows.Data.BindingExpressionBase.OnAttach(DependencyObject d, DependencyProperty dp)
   at System.Windows.StyleHelper.GetInstanceValue(UncommonField`1 dataField, DependencyObject container, FrameworkElement feChild, FrameworkContentElement fceChild, Int32 childIndex, DependencyProperty dp, Int32 i, EffectiveValueEntry& entry)
   at System.Windows.StyleHelper.GetChildValueHelper(UncommonField`1 dataField, ItemStructList`1& valueLookupList, DependencyProperty dp, DependencyObject container, FrameworkObject child, Int32 childIndex, Boolean styleLookup, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetChildValue(UncommonField`1 dataField, DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, EffectiveValueEntry& entry, ValueLookupType& sourceType, FrameworkElementFactory templateRoot)
   at System.Windows.StyleHelper.GetValueFromTemplatedParent(DependencyObject container, Int32 childIndex, FrameworkObject child, DependencyProperty dp, FrugalStructList`1& childRecordFromChildIndex, FrameworkElementFactory templateRoot, EffectiveValueEntry& entry)
   at System.Windows.FrameworkElement.GetValueFromTemplatedParent(DependencyProperty dp, EffectiveValueEntry& entry)
   at System.Windows.FrameworkElement.GetRawValue(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& entry)
   at System.Windows.FrameworkElement.EvaluateBaseValueCore(DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry& newEntry)
   at System.Windows.DependencyObject.EvaluateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry newEntry, OperationType operationType)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
```

**Comment by JosefNemec** [comment]
The only possibility for it to not work with 10.37 is if you are binding to a value that's not a boolean. Which would be an issue on your side. I probably should have added check for that as well, but I'm not most likely not going to make an update just for this.

**Comment by darklinkpower** [comment]
The value using the `PluginStatus` markup should be returning a boolean value shouldn't it? According to: https://api.playnite.link/docs/tutorials/themes/extensionIntegration.html#detecting-if-an-extension-is-installed

> PluginStatus automatically converts to Visibility value if used on Visibility property, it's not needed to use converter in that case. _**In other cases it return's bool value**_, true if a plugin is installed.

Since `Tag` is not a `Visibililty` property I think the usage should be correct and valid; the Markup should be setting a boolean and it works without issues on runtime. I might be wrong but without knowing the code behind this, I'm wondering if the issue is that the markup is not working correctly during Design/Blend execution only.

**Comment by JosefNemec** [comment]
Yeah might be that PluginStatus has some issue when running inside Blend.

**Comment by JosefNemec** [comment]
My bad, the converter in question is duplicated in the code base and I fixed the issue in wrong instance :( 

Will be fixed in next P10 update.
