### ISSUE TITLE
Cursor search box jumping

### ISSUE THREAD

**Issue by By6r9** [JosefNemec/Playnite#779]
Type some characters into search or filter box, move cursor back one or more characters, start typing, cursor will jump to the end of a box.

**Comment by JosefNemec** [comment]
Fixed in 4.59

**Comment by By6r9** [comment]
I can still reproduce it in 4.61. I will post video on discord.

**Comment by JosefNemec** [comment]
Fixed in 4.64
